#!/bin/sh
# brainfuck to Arborealis transcompiler

if [ $# != 1 ]; then
	echo "Usage: bf2arb <bf file>"
	exit
fi

if [ ! -f "$1" ]; then
	echo "Error: '$1' is not a valid file"
	exit
fi

sed 's/>/\\>(/g' "$1" > "${1%%.*}.arb"
